version: "3.0"

services: 

  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    image: fldu/client
    links: 
      - broker
      - db
      - logging
    
  broker:
    image: rabbitmq

  logging:
    image: rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    image: fldu/workers
    links:
      - broker
      - db
      - logging
    deploy:
      replicas: 4

  db:
    image: mariadb
    env_file: ./app/.env
    volumes:
      - db:/var/lib/mysql

volumes: 
  db: